### ISSUE TITLE
When have inline link relation A->B, can't query B->A

### ISSUE THREAD

**Issue by playerx** [prisma/Mongo-Connector-Preview#13]
I've simple data model:
```gql
type User {
	id: ID! @id
	name: String!
	accounts: [Account!]!
}

type Account {
	id: ID! @id
	balance: Float!
	user: User! @relation(link: INLINE)
}
```

I can query `user` from Account, but can't query `accounts` from User. I know it will be expensive operation for Mongodb, but still there should be ability to query it if its necessary. Now it returns empty array

Example mutation & query:
```gql
mutation {
  createUser(data: { name: "Ezeki", accounts: { create: { balance: 101 } } }) {
    id
    name
    accounts { # It will return an empty array
      id
      balance
    }
  }
}
```

**Comment by giggo1604** [comment]
Same problem here but I'm not sure if this might be the expected behavior or if indeed prisma can resolve such a relation. I would highly appreciate it if someone could clarify this.

**Comment by do4gr** [comment]
This should be working in both directions. I'll investigate tomorrow.

**Comment by do4gr** [comment]
I just tested it with the latest alpha and it seems to be working as expected for me. Queries also work in both sides. Can you give some more details about your setup? Which version are you running? Are you running against Mongo proper or a compliant DB like Cosmos?

<img width="1278" alt="bildschirmfoto 2018-12-03 um 09 34 35" src="https://user-images.githubusercontent.com/16278407/49362285-b387e380-f6de-11e8-8e80-12a95a93458f.png">

**Comment by giggo1604** [comment]
Just verified that there was nothing wrong on my side (as far as I know). I tested it on prima:1-22-beta
with mongodb 3.6.

```yml
version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.22-beta
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        managementApiSecret: my-server-secret-123
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo:27017

  mongo:
    container_name: mongo
    image: mongo:3.6
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
```
![screenshot from 2018-12-03 13-53-32](https://user-images.githubusercontent.com/4090913/49375030-6f5b0a00-f703-11e8-99d1-09bb603f124f.png)

**Comment by playerx** [comment]
@do4gr 
I've tried also with latest `1.23-alpha` and have same problem

## docker-compose.yaml
```yml
version: '3'

services:
  prisma:
    image: prismagraphql/prisma:1.23-alpha
    restart: always
    ports:
    - "4468:4466"
    environment:
      PRISMA_CONFIG: |
        # managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          default:
            connector: mongo
            uri: mongodb://prisma:prisma@mongo:27017/admin

  mongo:
    image: mongo:3.6
    restart: always
    ports:
    - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: prisma
      MONGO_INITDB_ROOT_PASSWORD: prisma
    volumes:
      - mongo:/var/lib/mongo

volumes:
  mongo:
```

## datamodel.graphql
```gql
type User {
	id: ID! @id
	name: String!
	accounts: [Account!]!
}

type Account {
	id: ID! @id
	balance: Float!
	user: User! @relation(link: INLINE)
}
```

## query
```gql
mutation {
  createUser(data: { name: "Ezeki", accounts: { create: { balance: 101 } } }) {
    id
    name
    accounts { # It will return an empty array
      id
      balance
    }
  }
}
```
